anticheat:
  compatibility:
    auto-adjust: true
    disable-incompatible: true
    
  alerts:
    enabled: true
    console: true
    staff: true
    format: "&8[&cSentinelAC&8] &f%player% &7failed &c%check% &8(&7x%violations%&8) &8[&7%ping%ms&8]"
    
  checks:
    fly:
      enabled: true
      max-violations: 10
      sensitivity: 3
      check-elytra: true
      teleport-to-ground: true
      
    speed:
      enabled: true
      max-violations: 15
      sensitivity: 3
      threshold: 1.2
      ice-multiplier: 2.5
      
    nofall:
      enabled: true
      max-violations: 8
      sensitivity: 5
      min-fall-distance: 3.0
      
    killaura:
      enabled: true
      max-violations: 5
      sensitivity: 5
      max-angle: 90.0
      
    reach:
      enabled: true
      max-violations: 5
      sensitivity: 5
      max-distance: 4.2
      
    fastbreak:
      enabled: true
      max-violations: 12
      sensitivity: 5
      tolerance: 0.8
      
    inventory:
      enabled: true
      max-violations: 8
      sensitivity: 5
      max-clicks-per-second: 20

punishments:
  fly:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fFlight\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  speed:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fSpeed\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  nofall:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fNoFall\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  killaura:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fKillAura\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  reach:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fReach\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  fastbreak:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fFastBreak\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."
  inventory:
    - "kick %player% \n§cSentinelAC §8» §7You have been removed from the server.\n\n§cCheat detected: §fInventoryMove\n§cPing: §f%ping%ms\n§cTPS: §f20.0\n\n§7If you believe this is a false positive, please report it."